# Generated by Django 5.2 on 2025-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
