# Generated by Django 5.2 on 2025-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
